# Generated by Django 3.2.5 on 2021-07-08 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('category', models.CharField(max_length=20)),
                ('discount', models.IntegerField()),
                ('serving_time_period', models.TimeField()),
                ('estimated_cooking_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('status', models.CharField(max_length=20)),
                ('time_stamp', models.DateTimeField()),
                ('menu_item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Receipt_User_id', to='cafe.menuitems')),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.IntegerField()),
                ('cafe_space_position', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('birth_day', models.DateField()),
                ('password_to_login', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Receipts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('final_price', models.IntegerField()),
                ('total_price', models.IntegerField()),
                ('orders_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafe.orders')),
            ],
        ),
        migrations.AddField(
            model_name='orders',
            name='table_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Receipts_Orders_id', to='cafe.table'),
        ),
    ]
